uploads = []

[[generated]]
id = "phKaYk4ogEjBYbGh7kpOo"
uri = "file://client/public/opengraph.png"
type = "image"
title = "MIB global exchange opengraph"

[[generated]]
id = "r14vXuFH6CgIBel6J64iM"
uri = "file://client/public/mib-icon.png"
type = "image"
title = "MIB favicon icon"

[[outputs]]
id = "JxbMG6iCwgkLYXFE8yWL5"
uri = "file://forced_settlement_questions.md"
type = "text"
title = "거래 강제설정 로직 확인 질문지"

[[outputs]]
id = "8yTGYaQQ1mfAZy8tznOtH"
uri = "file://잔고보정_보고서.md"
type = "text"
title = "잔고 보정 보고서 (2026-03-12)"

[[outputs]]
id = "0Dq9pDAWH-AUY370smNgI"
uri = "file://잔고보정_목록.md"
type = "text"
title = "잔고 보정 목록 (2026-03-12)"
