// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gold-signal/Editorial.tsx": () => import("../components/mockups/gold-signal/Editorial.tsx"),
  "./components/mockups/gold-signal/LogoFacet.tsx": () => import("../components/mockups/gold-signal/LogoFacet.tsx"),
  "./components/mockups/gold-signal/LogoPulse.tsx": () => import("../components/mockups/gold-signal/LogoPulse.tsx"),
  "./components/mockups/gold-signal/LogoSovereign.tsx": () => import("../components/mockups/gold-signal/LogoSovereign.tsx"),
  "./components/mockups/gold-signal/Opulent.tsx": () => import("../components/mockups/gold-signal/Opulent.tsx"),
  "./components/mockups/gold-signal/Prestige.tsx": () => import("../components/mockups/gold-signal/Prestige.tsx"),
  "./components/mockups/mib-landing/LandingPreview.tsx": () => import("../components/mockups/mib-landing/LandingPreview.tsx"),
  "./components/mockups/mib-logo/LogoPreview.tsx": () => import("../components/mockups/mib-logo/LogoPreview.tsx")
};
